on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release'  # 显示在GitHub UI的描述
        required: true
        default: 'v1.0.0'  # 默认标签

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package -DskipTest -DaltDeploymentRepository

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: maven-artifact
        path: /home/runner/work/tabby-path-finder/tabby-path-finder.jar
